sudo: required
services:
    - docker

before_install:
  - docker build -t ashishdhawal/docker-reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true ashishdhawal/docker-reactapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-mac"
  env: "DockerReactMac-env"
  bucket_name: "elasticbeanstalk-us-east-2-171912905752"
  bucket_path: "docker-react-mac"
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY"
  secret-access_key:
    secure: "$AWS_SECRET_KEY"